// @ts-check
// `@type` JSDoc annotations allow editor autocompletion and type checking
// (when paired with `@ts-check`).
// There are various equivalent ways to declare your Docusaurus config.
// See: https://docusaurus.io/docs/api/docusaurus-config

import fs from 'node:fs';
import path from 'node:path';
import {themes as prismThemes} from 'prism-react-renderer';
import remarkMath from 'remark-math';
import rehypeKatex from 'rehype-katex';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// Single source of truth: the digest markdown lives in ../summaries (the exact
// path the Python pipeline writes to and mirrors to MinIO). Docusaurus reads it
// directly — no copy, no transform. The MDX-breaking characters in the digests
// (e.g. "<|Rotate|>", "loss < 1e-3") are handled by markdown.format = 'detect'
// below, which parses .md as CommonMark (literal '<'/'{') instead of MDX.
const SUMMARIES_DIR = path.resolve(__dirname, '..', 'summaries');

// Scan ../summaries for the newest daily_digest_YYYY-MM-DD.md and return its
// docs route (used by the homepage CTA). Falls back to '/docs' if none found.
function findLatestDigestRoute() {
  let best = null;
  const visit = (dir) => {
    let entries = [];
    try {
      entries = fs.readdirSync(dir, {withFileTypes: true});
    } catch {
      return;
    }
    for (const e of entries) {
      const full = path.join(dir, e.name);
      if (e.isDirectory()) visit(full);
      else if (e.isFile() && /daily_digest_\d{4}-\d{2}-\d{2}\.md$/.test(e.name)) {
        const rel = path.relative(SUMMARIES_DIR, full).replace(/\.md$/, '');
        const num = Number(e.name.replace(/\D/g, '').slice(0, 8));
        if (!best || num > best.num) best = {num, route: '/docs/' + rel};
      }
    }
  };
  visit(SUMMARIES_DIR);
  return best ? best.route : '/docs';
}

// --- Sidebar customization helpers -----------------------------------------
// The default autogenerated sidebar would label digests with the long H1 and
// sort alphabetically. We relabel to friendly dates and sort newest-first.
// This logic lives here (committed) rather than in _category_.json files
// inside summaries/ because that dir is gitignored and rebuilt from MinIO on
// CI — any config dropped there would be lost.

const MONTH_VI = {
  '01': 'Tháng 1',
  '02': 'Tháng 2',
  '03': 'Tháng 3',
  '04': 'Tháng 4',
  '05': 'Tháng 5',
  '06': 'Tháng 6',
  '07': 'Tháng 7',
  '08': 'Tháng 8',
  '09': 'Tháng 9',
  '10': 'Tháng 10',
  '11': 'Tháng 11',
  '12': 'Tháng 12',
};

// Parse the date out of a doc id like "2026/05/daily_digest_2026-05-01".
function parseDigest(id) {
  const m = String(id).match(/daily_digest_(\d{4})-(\d{2})-(\d{2})/);
  if (!m) return null;
  return {y: m[1], mo: m[2], d: m[3], num: Number(`${m[1]}${m[2]}${m[3]}`)};
}

// Numeric value used for sorting categories (year/month folder names) and
// docs (date as YYYYMMDD). Larger = newer.
function sortValue(item) {
  if (item.type === 'doc') {
    return parseDigest(item.id)?.num ?? -Infinity;
  }
  if (item.type === 'category') {
    // Uses the ORIGINAL folder label (a year like 2026 or month like 05).
    return Number(item.label) || 0;
  }
  return -Infinity;
}

// Relabel + reorder: friendly Vietnamese labels, newest first at every level.
function decorateSidebar(items) {
  return items
    .slice()
    .sort((a, b) => sortValue(b) - sortValue(a))
    .map((item) => {
      if (item.type === 'category') {
        return {
          ...item,
          label: MONTH_VI[item.label] || item.label,
          items: decorateSidebar(item.items),
        };
      }
      if (item.type === 'doc') {
        const date = parseDigest(item.id);
        return {
          ...item,
          label: date ? `${date.d}/${date.mo}/${date.y}` : item.label,
        };
      }
      return item;
    });
}

// ---------------------------------------------------------------------------

const latestDigestRoute = findLatestDigestRoute();

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: 'Daily Papers Digest',
  tagline: 'Tóm tắt bài báo Hugging Face hằng ngày',
  favicon: 'img/favicon.ico',

  // Future flags, see https://docusaurus.io/docs/api/docusaurus-config#future
  future: {
    v4: true, // Improve compatibility with the upcoming Docusaurus v4
  },

  // Set the production url of your site here
  url: 'https://gnust-company.github.io',
  // Set the /<baseUrl>/ pathname under which your site is served
  // For GitHub pages deployment, it is often '/<projectName>/'
  baseUrl: '/daily_papers_digest/',

  // GitHub pages deployment config.
  organizationName: 'gnust-company', // GitHub org that owns the repo.
  projectName: 'daily_papers_digest', // Usually your repo name.

  onBrokenLinks: 'throw',
  onBrokenAnchors: 'warn',

  // Parse .md as CommonMark (literal '<', '{') and .mdx as MDX. This lets the
  // raw digest markdown be served directly from ../summaries without escaping.
  markdown: {
    format: 'detect',
  },

  // Expose the newest digest route so the homepage can deep-link to it.
  customFields: {
    latestDigestRoute,
  },

  // Even if you don't use internationalization, you can use this field to set
  // useful metadata like html lang. Vietnamese content.
  i18n: {
    defaultLocale: 'vi',
    locales: ['vi'],
  },

  stylesheets: [
    {
      href: 'https://cdn.jsdelivr.net/npm/katex@0.16.11/dist/katex.min.css',
      type: 'text/css',
      integrity:
        'sha384-nB0miv6/jRmo5UMMR1wu3Gz6NLsoTkbqJghGIsx//Rlm+ZU03BU6SQNC66uf4l5+',
      crossorigin: 'anonymous',
    },
  ],

  presets: [
    [
      'classic',
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          // Read the digest markdown directly from ../summaries (single source
          // of truth; also mirrored to MinIO by the pipeline). No copy step.
          path: '../summaries',
          routeBasePath: 'docs',
          sidebarPath: './sidebars.js',
          // summaries/ is gitignored (rebuilt from MinIO on CI), so there is
          // no source file to link to — disable "edit this page".
          editUrl: undefined,
          showLastUpdateTime: false,
          sidebarItemsGenerator: async function sidebarItemsGenerator({
            defaultSidebarItemsGenerator,
            ...args
          }) {
            const items = await defaultSidebarItemsGenerator(args);
            return decorateSidebar(items);
          },
          // Math rendering ($...$ and $$...$$).
          remarkPlugins: [remarkMath],
          rehypePlugins: [rehypeKatex],
        },
        blog: {
          showReadingTime: true,
          feedOptions: {
            type: ['rss', 'atom'],
            xslt: true,
          },
          onInlineTags: 'warn',
          onInlineAuthors: 'warn',
          onUntruncatedBlogPosts: 'warn',
        },
        theme: {
          customCss: './src/css/custom.css',
        },
      }),
    ],
  ],

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      colorMode: {
        respectPrefersColorScheme: true,
      },
      navbar: {
        title: 'Daily Papers Digest',
        items: [
          {
            type: 'docSidebar',
            sidebarId: 'tutorialSidebar',
            position: 'left',
            label: 'Digest',
          },
          {to: '/blog', label: 'Blog', position: 'left'},
          {
            href: 'https://github.com/gnust-company/daily_papers_digest',
            label: 'GitHub',
            position: 'right',
          },
        ],
      },
      footer: {
        style: 'dark',
        links: [
          {
            title: 'Nội dung',
            items: [
              {
                label: 'Digest mới nhất',
                to: latestDigestRoute,
              },
              {
                label: 'Blog',
                to: '/blog',
              },
            ],
          },
          {
            title: 'Liên kết',
            items: [
              {
                label: 'Hugging Face Papers',
                href: 'https://huggingface.co/papers',
              },
              {
                label: 'GitHub',
                href: 'https://github.com/gnust-company/daily_papers_digest',
              },
            ],
          },
        ],
        copyright: `Copyright © ${new Date().getFullYear()} Daily Papers Digest. Built with Docusaurus.`,
      },
      prism: {
        theme: prismThemes.github,
        darkTheme: prismThemes.dracula,
      },
    }),
};

export default config;
